#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoundedImageViewSample.Resource", IsApplication=true)]

namespace RoundedImageViewSample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.0.0.73")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int action_list = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int riv_border_color = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int riv_border_width = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int riv_corner_radius = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int riv_corner_radius_bottom_left = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int riv_corner_radius_bottom_right = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int riv_corner_radius_top_left = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int riv_corner_radius_top_right = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int riv_mutate_background = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int riv_oval = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int riv_tile_mode = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int riv_tile_mode_x = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int riv_tile_mode_y = 2130837515;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int border = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int color_accent = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int color_primary = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int color_primary_dark = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040001
			public const int black_white_tile = 2130968577;
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int photo1 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int photo2 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int photo3 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int photo4 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int photo5 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int photo6 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int photo7 = 2130968584;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int clamp = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int fragment_container = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int imageView1 = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int main_list = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int mirror = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int playPause = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int repeat = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int spinner_nav = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int textView1 = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int textView2 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int textView3 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int toolbar = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int Main = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int PicassoItem = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int Rounded = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int RoundedItem = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int RoundedItemSelect = 2131099652;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int menu_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int define_roundedimageview = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int library_roundedimageview_author = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int library_roundedimageview_authorWebsite = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int library_roundedimageview_isOpenSource = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int library_roundedimageview_libraryDescription = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int library_roundedimageview_libraryName = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int library_roundedimageview_libraryVersion = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int library_roundedimageview_libraryWebsite = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int library_roundedimageview_licenseId = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int library_roundedimageview_repositoryLink = 2131230730;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x101011D,0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B }
			public static int[] RoundedImageView = new int[] {
					16843037,
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515};
			
			// aapt resource value: 0
			public const int RoundedImageView_android_scaleType = 0;
			
			// aapt resource value: 1
			public const int RoundedImageView_riv_border_color = 1;
			
			// aapt resource value: 2
			public const int RoundedImageView_riv_border_width = 2;
			
			// aapt resource value: 3
			public const int RoundedImageView_riv_corner_radius = 3;
			
			// aapt resource value: 4
			public const int RoundedImageView_riv_corner_radius_bottom_left = 4;
			
			// aapt resource value: 5
			public const int RoundedImageView_riv_corner_radius_bottom_right = 5;
			
			// aapt resource value: 6
			public const int RoundedImageView_riv_corner_radius_top_left = 6;
			
			// aapt resource value: 7
			public const int RoundedImageView_riv_corner_radius_top_right = 7;
			
			// aapt resource value: 8
			public const int RoundedImageView_riv_mutate_background = 8;
			
			// aapt resource value: 9
			public const int RoundedImageView_riv_oval = 9;
			
			// aapt resource value: 10
			public const int RoundedImageView_riv_tile_mode = 10;
			
			// aapt resource value: 11
			public const int RoundedImageView_riv_tile_mode_x = 11;
			
			// aapt resource value: 12
			public const int RoundedImageView_riv_tile_mode_y = 12;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
