// <auto-generated />
namespace API.MerchPlus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Membertableupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Membertableupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201610160245551_Member table updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
