// <auto-generated />
namespace API.MerchPlus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MembertabelnowhasTitlefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MembertabelnowhasTitlefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201610012135187_Member tabel now has Title field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
