// <auto-generated />
namespace API.MerchPlus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsertablenowhascustomfieldsforMerchPlusapplicationuse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsertablenowhascustomfieldsforMerchPlusapplicationuse));
        
        string IMigrationMetadata.Id
        {
            get { return "201609281740459_User table now has custom fields for MerchPlus application use"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
